### ISSUE TITLE
[Request] Add dimension whitelist

### ISSUE THREAD

**Issue by ulk-underscore** [The-Fireplace-Minecraft-Mods/Unforgiving-Void-Forge#1]
Can you add a per-dimension filter?
I'd like your mod to apply to the overworld and the original to the end, it makes so much sense with the minecraft "lore" (going deeper achievement and the sarcastic end of a sandbox game).

**Comment by The-Fireplace** [comment]
That's an interesting idea. I'll run it by the author of Forgiving Void and see what we can do.

**Comment by The-Fireplace** [comment]
I've done my part of it.

**Comment by The-Fireplace** [comment]
And, Forgiving Void is updated with theirs. Enjoy!

**Comment by ulk-underscore** [comment]
Thanks!
