### ISSUE TITLE
Mods repost authorization request

### ISSUE THREAD

**Issue by Aemande123** [The-Fireplace-Minecraft-Mods/Unforgiving-Void-Forge#10]
Hello there
Your mods are great!!!
can I move your mods to mcbbs?
mcbbs:https://www.mcbbs.net/
mcbbs is the largest minecraft fan forum in China

I will not provide download sources other than Curseforge
and highlight your Patreon.

I'm sorry to ask questions here, because of GFW, I cannot register for a twitch account, so I cannot ask questions on Curseforge.

**Comment by The-Fireplace** [comment]
Go ahead.

**Comment by Aemande123** [comment]
> Go ahead.

Thank you very much
