### ISSUE TITLE
[1.15.2-1.0.4] ticking entity

### ISSUE THREAD

**Issue by kreezxil** [The-Fireplace-Minecraft-Mods/Unforgiving-Void-Forge#11]
A player of my Foreshadowing modpack is reporting this error occasionally when teleporting, says their client crashes out.

https://gist.github.com/defranke00/8a7c2b9671ae9b0467566dbbf8308cc6

reported at: https://github.com/kreezxil/foreshadowing/issues/64

**Comment by The-Fireplace** [comment]
Yeah, that happens every once in a while, and I've been unable to find the cause. I should be able to fix it when I update to 1.16 thanks to the new dimension changing logic that came with being able to spawn in the Nether, but I have no plans to fix this on 1.15.2.
