### ISSUE TITLE
[Request] Add a spawn platform

### ISSUE THREAD

**Issue by ulk-underscore** [The-Fireplace-Minecraft-Mods/Unforgiving-Void-Forge#2]
So much lava, so little luck...

**Comment by The-Fireplace** [comment]
This is already coded in with the "saveFromLava" config option, where it spawns is just a little unpredictable. I'll see if I can improve it in the next update.

**Comment by The-Fireplace** [comment]
Update: I realized I never actually released that update. It's included in version 1.0.2, which I just released.
