### ISSUE TITLE
Not functioning right

### ISSUE THREAD

**Issue by ghost** [The-Fireplace-Minecraft-Mods/Unforgiving-Void-Forge#5]
Forge 2768
Less Forgiving Void 1.0.1

I get transported to the overworld instead of the nether and am given obsidian. Nothing in the logfile says anything is going wrong.

**Comment by ghost** [comment]
Bump

**Comment by ghost** [comment]
I have finally been able to do some further testing on this. It appears to be a conflict with OTG and Biome Bundle. I'm unsure quite what about them causes the issue, the dimension id's are the same and vanilla nether portals function normally. Does this mod use any special teleport functions?

**Comment by ghost** [comment]
1 month poke, just seeing where this is at :)

**Comment by The-Fireplace** [comment]
Tbh I haven't worked on this mod at all in the last two months. I don't have a lot of time right now.

**Comment by ghost** [comment]
Alright, I understand real life is priority :)

**Comment by The-Fireplace** [comment]
Alright, I've done what I can to solve the issue. No promises that it'll be perfect, this is kind of a derpy mod, but it should at least avoid giving you obsidian if you don't make it to the nether. Try out version 1.0.2.
