### ISSUE TITLE
Teleporting multiple times in the nether

### ISSUE THREAD

**Issue by Cazadorsniper** [The-Fireplace-Minecraft-Mods/Unforgiving-Void-Forge#6]
For issues:
It seems when on a multiplayer server, if the player falls into the void to get to the nether, the player teleports several times before stopping some where sometimes the player gets disconnected and can't log in until the their playerdata is deleted. This is pretty much the same issue as #3 .

This has been reported to me in https://github.com/Cazadorsniper/PO3/issues/332 too.

**Comment by PhunStyle** [comment]
To add to above, some (potentially) helpful version numbers:

- **Minecraft version:** 1.12.2
- **Mod version:** UnforgivingVoid-1.12.2-1.0.2.jar
- **Forge version/build:** Forge Mod Loader version 14.23.5.2836
- **Versions of any mods potentially related to the issue:**
  No idea, but all the mod versions should be on the project ozone 3 forge page.

- **Any relevant screenshots/videos are greatly appreciated:**
  https://www.twitch.tv/videos/416969261

- **For crashes:**
  - Steps to reproduce:
  Fall into the void.

**Comment by The-Fireplace** [comment]
Teleporting into the nether has always been somewhat derpy, but I'll see if I can do anything more to smooth it out. The player data having to be deleted is my biggest worry, can you post the server logs for when someone tries to log in but the data has to be deleted?

**Comment by PhunStyle** [comment]
Yeah my friend got the glitch just now, i'll capture the logs for you.
https://pastebin.com/Ga61gFyx

I got this from debug.log, hopefully that's the right place. Also this spams the console SO MUCH, like dozens of times per second. If he stayed logged in the server would have crashed.

Edit: Here's a log file from the first occurrence of when he logs in:
https://pastebin.com/5dKxLfVb

**Comment by TehVampire** [comment]
it seems unforgiving void tries to find an empty 'spawn' point to land you in the nether when the obsidian platforms are enabled. it will keep sending you to the nether untill it either finds an 'eligble' empty spot or untill the server crashes because of ticks time out.

Our nether portal is around x-17 z-50
My before last fall into the void sent me to x-1060 z280
My last fall into the void sent x1150 z1530

So it probably also makes new chunks while teleporting you and goes further and further away.

**Comment by Loriborn** [comment]
I can confirm this happens pretty regularly in our case too.

**Comment by Danapel** [comment]
same here! I removed the mod from the server to see if it would just kill me but still tries to teleport me for some reason. I hope a fix comes for this soon so I can re-add the mod, I love the concept.

**Comment by 1time** [comment]
any updates on that matter would be much appreciated

**Comment by The-Fireplace** [comment]
Update: I still have no idea why it does this or how to fix it.

**Comment by Cazadorsniper** [comment]
I'm just throwing an idea out but maybe add a delay between teleportations?

**Comment by The-Fireplace** [comment]
Alright, I think I might have fixed this in version 1.0.5. It's hard to know for sure because it's kind of random, but I've jumped into the void with my attempted fix over 20 times and not run into the issue.

**Comment by The-Fireplace** [comment]
Let me know if this issue persists and I will re-open.
