### ISSUE TITLE
[feature request] Allow us to specify the exact point the player will spawn

### ISSUE THREAD

**Issue by Winddbourne** [The-Fireplace-Minecraft-Mods/Unforgiving-Void-Forge#7]
I wanted to always have the player spawn into the nether at a set location, a lobby I created and placed using recurrent complex.  Unfortunately, when I got into the configuration file I can only specify a range for x/z and no option is given to specify a Y location at all. 

Could you please add an option that lets us move the player in at a specific spot every time? Thank you. :)

**Comment by The-Fireplace** [comment]
If you'd still like this feature, you can request it on the [new issue tracker](https://github.com/The-Fireplace-Minecraft-Mods/Unforgiving-Void/issues).
