### ISSUE TITLE
Spawning in the wrong dimension!

### ISSUE THREAD

**Issue by SkippyMitch** [The-Fireplace-Minecraft-Mods/Unforgiving-Void-Forge#8]
UnforgivingVoid-1.12.2-1.0.2 

Hey! I'm in love with this mod, but I can't get it to spawn me in the nether.. instead it spawns me in the Overworld, I'm fairly positive this could be because of a mod I'm using, called "Vertically Stacked Dimensions" Also I am using OTG for the overworld

I would be so happy if this can be remedied anything else you need to know I will oblige

**Comment by SkippyMitch** [comment]
Actually, now I see that there is already a similar issue posted where OTG + Biome bundle was culprit... 
:(

**Comment by The-Fireplace** [comment]
This is most likely caused by OTG. Closing this issue in favor of #9, which has more details.
