### ISSUE TITLE
[ Compatibility ] Mod doesnt work with OTG installed

### ISSUE THREAD

**Issue by Phorcis** [The-Fireplace-Minecraft-Mods/Unforgiving-Void-Forge#9]
Minecraft 1.12.2
Forge 14.23.5.2838
UnforgivingVoid 1.0.2
Open Terrain Generator v8 r1

`Error: Unable to teleport player to the Nether from the void. Unfortunately, the player will die. If this happens, please report it.`

Teleporting to nether doesnt work even with **I:triggerAtY=-1**

Chat with OTG developer:

 

> Phorcis
> Hello!
> Unforgiving Void 1.12.2 v1.0.2 doesnt work with otg 8 r1
> no crashes, no errors, just mod not working
>  
> Witness The Pitness
> probably to be expected since OTG has its own mechanics for falling out of the bottom of the map
>  
> Phorcis
> aw, ill check
> are there any ways to change this? I want to go to nether when I fall out
> or should I contact UV's author?
>  
> Witness The Pitness
> not sure, it's unlikely to get fixed on our end because OTG is a massive mod with only one dev with not a lot of free time

**Comment by The-Fireplace** [comment]
This isn't too likely to get fixed on my end either as I'd have to find a way to override whatever OTG is doing. I may, however, try to make a change to OTG that fixes the issue and see if the author will accept it.

**Comment by The-Fireplace** [comment]
If this is still a problem when I update to 1.16, please open another issue and I'll see what I can do to fix it.
